version: '3.6'

services:

  redis:
    image: redis:alpine
    network_mode: host
    ports:
      - "6380:6379"
    expose:
      - "6380"

  celery:
    build: ./
    command: celery -A core worker --loglevel=INFO --concurrency=10
    network_mode: host

    depends_on:
      - redis
  celery-beat:
    build: ./
    network_mode: host

    command: celery -A core beat -l info
    depends_on:
      - redis