version: '3.6'

services:

  redis:
    image: redis:alpine
    networks:
      - main

  celery:
    build: ./
    command: celery -A core worker --loglevel=INFO --concurrency=10

    depends_on:
      - redis
  celery-beat:
    build: ./

    command: celery -A core beat -l info
    depends_on:
      - redis